from __future__ import annotations  # Включаем отложенную обработку типов.

# Form implementation generated from reading ui file 'C:\Python_projects\Geophysics\with_nn\deghost_with_ai\workshot\node_edit_canvas.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # Импортируем Qt-модули формы.


class Ui_node_canvas(object):  # Объявляем форму canvas из Qt Designer.
    def setupUi(self, node_canvas):  # Настраиваем виджеты формы.
        node_canvas.setObjectName("node_canvas")  # Задаём имя корневого виджета.
        node_canvas.resize(879, 591)  # Задаём исходный размер формы.
        sizePolicy = QtWidgets.QSizePolicy(  # Создаём политику растяжения.
            QtWidgets.QSizePolicy.Policy.Expanding,  # Растягиваем по ширине.
            QtWidgets.QSizePolicy.Policy.Expanding,  # Растягиваем по высоте.
        )  # Завершаем создание политики размера.
        sizePolicy.setHorizontalStretch(0)  # Отключаем доп. растяжение ширины.
        sizePolicy.setVerticalStretch(0)  # Отключаем доп. растяжение высоты.
        sizePolicy.setHeightForWidth(  # Учитываем зависимость высоты от ширины.
            node_canvas.sizePolicy().hasHeightForWidth()  # Берём флаг виджета.
        )  # Завершаем настройку политики.
        node_canvas.setSizePolicy(sizePolicy)  # Применяем политику размера.
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(node_canvas)  # Корневой layout.
        self.verticalLayout_2.setObjectName("verticalLayout_2")  # Имя layout.
        self.verticalLayout = QtWidgets.QVBoxLayout()  # Layout для графа.
        self.verticalLayout.setObjectName("verticalLayout")  # Имя layout графа.
        self.verticalLayout_2.addLayout(self.verticalLayout)  # Вкладываем layout.

        self.retranslateUi(node_canvas)  # Применяем переводимые строки.
        QtCore.QMetaObject.connectSlotsByName(node_canvas)  # Подключаем слоты.

    def retranslateUi(self, node_canvas):  # Настраиваем переводимые строки.
        _translate = QtCore.QCoreApplication.translate  # Берём функцию перевода.
        node_canvas.setWindowTitle(_translate("node_canvas", "Form"))  # Заголовок.
