# Form implementation generated from reading ui file 'C:\Python_projects\Geophysics\with_nn\deghost_with_ai\workshot\launch_screen.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_launch_screen(object):
    def setupUi(self, launch_screen):
        launch_screen.setObjectName("launch_screen")
        launch_screen.resize(480, 380)
        launch_screen.setMinimumSize(QtCore.QSize(480, 380))
        self.gridLayout_2 = QtWidgets.QGridLayout(launch_screen)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_training = QtWidgets.QPushButton(parent=launch_screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_training.sizePolicy().hasHeightForWidth())
        self.btn_training.setSizePolicy(sizePolicy)
        self.btn_training.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.btn_training.setObjectName("btn_training")
        self.gridLayout.addWidget(self.btn_training, 0, 1, 1, 1)
        self.btn_processing = QtWidgets.QPushButton(parent=launch_screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_processing.sizePolicy().hasHeightForWidth())
        self.btn_processing.setSizePolicy(sizePolicy)
        self.btn_processing.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.btn_processing.setObjectName("btn_processing")
        self.gridLayout.addWidget(self.btn_processing, 1, 1, 1, 1)
        self.btn_synthetic = QtWidgets.QPushButton(parent=launch_screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_synthetic.sizePolicy().hasHeightForWidth())
        self.btn_synthetic.setSizePolicy(sizePolicy)
        self.btn_synthetic.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.btn_synthetic.setObjectName("btn_synthetic")
        self.gridLayout.addWidget(self.btn_synthetic, 1, 2, 1, 1)
        self.btn_testing = QtWidgets.QPushButton(parent=launch_screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_testing.sizePolicy().hasHeightForWidth())
        self.btn_testing.setSizePolicy(sizePolicy)
        self.btn_testing.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.btn_testing.setObjectName("btn_testing")
        self.gridLayout.addWidget(self.btn_testing, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(launch_screen)
        QtCore.QMetaObject.connectSlotsByName(launch_screen)

    def retranslateUi(self, launch_screen):
        _translate = QtCore.QCoreApplication.translate
        launch_screen.setWindowTitle(_translate("launch_screen", "Выбери режим работы"))
        self.btn_training.setText(_translate("launch_screen", "Обучение"))
        self.btn_processing.setText(_translate("launch_screen", "Обработка"))
        self.btn_synthetic.setText(_translate("launch_screen", "Синтетика"))
        self.btn_testing.setText(_translate("launch_screen", "Тестирование"))
